export const WORKSPACE_DEFAULT_SORT = 'createdAt@asc';
export const WORKSPACE_DEFAULT_PAGE = 1;
export const WORKSPACE_DEFAULT_PER_PAGE = 20;
export const WORKSPACE_DEFAULT_AVAILABLE_SORT = ['name', 'createdAt'];
export const WORKSPACE_DEFAULT_AVAILABLE_SEARCH = ['name'];
export const WORKSPACE_DEFAULT_ACTIVE = [true, false];

export const WORKSPACE_SERVICE = 'WORKSPACE_SERVICE';
export const WORKSPACE_USERS_SERVICE = 'WORKSPACE_USERS_SERVICE';
export const WORKSPACE_INVITATIONS_SERVICE = 'WORKSPACE_INVITATIONS_SERVICE';
export const WORKSPACE_TEAM_USE_CASE = 'WORKSPACE_TEAM_USE_CASE';
